Repository IT-Academy-BCN/ita-profiles, pull requests merged in 2024-12, with the labels that each got.

#462 feature: create input component
  package-lock.json
  package.json
  src/__tests__/components/Input.test.tsx
  src/components/atoms/Input.tsx
Labels: frontend, feature

#461 427 create card component
  src/__tests__/components/atoms/Card.test.tsx
  src/components/atoms/Card.tsx
Labels: frontend, feature

#441 430 fe create modal component
  src/__tests__/components/molecules/Modal.test.tsx
  src/components/molecules/Modal.tsx
  types.ts
Labels: frontend, feature

#460 fixing imageStorage
  app/Http/Controllers/api/Student/AddStudentImageController.php
  app/Http/Controllers/api/Student/UpdateStudentImageController.php
  app/Http/Requests/UpdateImageStudentRequest.php
  entrypoint.sh
Labels: dreaming of a better world

#469 hotfix: 468-make-sure-that-at-least-one-resume-have-no-bootcamp-associated
  database/seeders/ResumeBootcampSeeder.php
Labels: hotfix, backend

#464 455-refactor-registercontroller
  app/Http/Controllers/api/Auth/RegisterController.php
  app/Service/User/UserRegisterService.php
  tests/Feature/Controller/User/RegisterUserControllerTest.php
  tests/Feature/Service/User/RegisterUserServiceTest.php
Labels: backend, refactor

#449 429 create title component
  src/__tests__/components/atoms/Title.test.tsx
  src/components/atoms/Title.tsx
Labels: frontend, feature

#467 Create a faker function to generate valid DNI during seeding
  database/factories/UserFactory.php
Labels: backend, feature

#476 428 create label component
  src/__tests__/components/atoms/Label.test.tsx
  src/components/atoms/Label.tsx
Labels: frontend, refactor

#478 fixing routes
  routes/api/v1.php
Labels: hotfix

#465 Changes on readability of InvalidCredentialsException
  app/Exceptions/InvalidCredentialsException.php
Labels: backend
